services:
  petpalDB:
    image: postgis/postgis:12-3.4-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: petpal_db
      #IF using WSL subsystem on windows then uncomment PGDATA  
      #PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - "./postgres_data:/var/lib/postgresql@12/data:rw"
  
  backend:
    image: anhtuansggd/backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    ports: 
      - 8081:8081
    environment:
      DB_URL: jdbc:postgresql://petpalDB:5432/petpal_db
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - petpalDB
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_SERVER_HOST: petpalDB
      PGADMIN_DEFAULT_SERVER_PORT: 5432
      PGADMIN_DEFAULT_SERVER_USER: admin
      PGADMIN_DEFAULT_SERVER_PASSWORD: admin
    ports:
      - "5050:5050"
    depends_on:
      - petpalDB
    
#PERSISTENT VOLUMES
volumes:
  petpalDB:
    driver: local
