services:
  petpalDB:
    image: postgis/postgis:12-3.4-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: petpal_db
      #IF using WSL subsystem on windows then uncomment PGDATA  
      #PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - "./postgres_data:/var/lib/postgresql@12/data:rw"
  
  backend:
    image: anhtuansggd/petpal_backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    ports: 
      - 8081:8081
    environment:
      DB_URL: jdbc:postgresql://petpalDB:5432/petpal_db
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - petpalDB
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_SERVER_HOST: petpalDB
      PGADMIN_DEFAULT_SERVER_PORT: 5432
      PGADMIN_DEFAULT_SERVER_USER: admin
      PGADMIN_DEFAULT_SERVER_PASSWORD: admin
    ports:
      - "5050:5050"
    depends_on:
      - petpalDB

  webserver:
    image: nginx:1.27.0-alpine3.19

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    # 
    ports:
      - 3000
    depends_on:
      - webserver
      - backend
    volumes:
    - ./frontend:/app
    user: nextjs
  
  ssl-service:
    image: certbot/certbot:amd64-v2.8.0
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - frontend
    command:
      - renew
      # Certonly command did not run due to 'chicken and egg' problem:
      # Nginx need the certificate, but Certbot needs access on Nginx cert folder 
      #
      # -> solution: comment block that use https 443 in nginx.conf
      #              then restart nginx, and generate initial cert with command:
      # 'certbot certonly --webroot -w /var/www/certbot --email anhtuan.sggd@gmail.com -d softwares.systems -d www.softwares.systems --agree-tos --no-eff-email --force-renewal'
      #              now the cert is generated and the commented code in nginx.conf can be uncommented
      #
      #
      #- certonly
      #- --webroot 
      #- -w 
      #- /var/www/certbot
      #- --email=anhtuan.sggd@gmail.com 
      #- -d 
      #- softwares.systems
      #- -d 
      #- www.softwares.systems 
      #- --agree-tos
      #- --no-eff-email

  nginx:
    image: nginx:1.27.0-alpine3.19
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - ssl-service
      - frontend
#PERSISTENT VOLUMES
volumes:
  petpalDB:
    driver: local
