
import NavBar from "./components/NavBar";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={'flex flex-col w-screen h-screen ' + inter.className}>
        <NavBar />
        <div className='grow'>
          {children}
        </div>
      </body>
    </html>
  );
}
